* <2015-09-02 周三> 
** 【京东2016校招】京东广告部大数据挖掘组 - 诚招应届毕业生加盟 
【公司和部门介绍】 
京东是中国最大的零售企业，无论线上和线下。同时，京东的发展趋势远超电商大盘，销售额年同比增长75%以上。去年5月纳斯达克上市以来，京东股价已经上涨了接近80%，超过销售额的涨幅。 

京东数字营销业务部成立于2014年初，部门主要负责两个任务，给京东引流和把京东的流量变现。引流就是在网上打广告，引导用户去京东买东西。变现就是给京东平台上的商家和京东的供货商、品牌商提供广告营销服务。所以，我们数字营销业务部的业务范围覆盖了在线广告的各个环节，包括效果广告、品牌广告、搜索广告、展示广告、DSP、AdExchange。我们致力于打造世界一流的电商广告及营销平台，我们的产品京准通（http://jzt.jd.com 

 

）已于2014年9月上线，目前处在高速发展阶段。 

在线广告是技术密集型行业。要想在合适的时间地点给合适的人展现合适的广告，只能靠技术来实现。既然数字营销业务部的业务范围覆盖了在线广告的各个环节，我们更加渴求各种各样的技术人才加盟。京东数字营销业务部拥有互联网广告业内一流的技术团队，主要成员均来自百度、腾讯、雅虎等业界知名公司，有着丰富的互联网广告从业经验。我们意识到技术人才能够make so much difference，更让我们更加渴求更多技术人才加盟。 

【工作内容】 
我们在进行的工作包括， 
1，研发大数据处理系统：处理京东每日百亿级的广告请求、曝光、点击数据，京东站内的海量用户行为、订单转化数据； 
2，解决大数据处理的关键问题：数据传输、流式拼接、数据的可靠性/事务性保证、在线/离线的特征计算与存储、分布式机器学习算法等； 
3，机器学习算法应用于广告：研究各类机器学习算法，应用无监督挖掘、半监督/有监督的机器学习、异常检测、用户行为建模、订单跟踪、rule-base、model-base的大数据处理算法。 

【职位需求】 
1，熟悉C++、JAVA、python等编程技术，编程能力强 
2，熟悉大数据技术，包括spark、storm、MPI、hadoop、hive、pig等 
3，掌握机器学习算法，包括无监督聚类算法，异常检测，gbdt、svm、dnn等机器学习算法 
4，善于学习各种新技术 
5，能够团队合作，愿意沟通交流 

你将与行业顶尖的专家共事，获得优厚的待遇、良好的工作环境。快来加入我们吧！ 

请尽快将简历发送到邮箱：landy@jd.com 
** 【京东2016校招】京东广告部算法组 - 诚招应届毕业生加盟
【工作内容】 
我们在进行的工作包括， 
1，广告机制研究：流量变现方法，电商广告效果提升方法，广告生态建设;  
2，广告算法优化：个性化推荐等触发算法，基于点击率预估、ROI预估等排序策略，smartprice等广告定价策略，引流价值优化算法;  
3，机器学习算法应用：研究各类机器学习、深度学习、卷积神经网络等算法，应用于广告业务中，实现技术驱动的变现和引流效果提升;  
4，算法架构和性能优化：实现数据流实时处理、大规模特征存储，分布式机器学习的模型训练、分发、在线学习和预测，算法性能持续优化，基于GPU的深度学习架构和算法研发。 

【职位需求】 
1，熟悉C++、JAVA、python等编程技术，编程能力强 
2，熟悉各类机器学习算法，包括LR、SMV、DNN、CNN等，能够理解算法原理，并有能力研究和优化算法 
3，善于学习各种新技术 
4，能够团队合作，愿意沟通交流 

你将与行业顶尖的专家共事，获得优厚的待遇、良好的工作环境。快来加入我们吧！ 

请将简历发送到邮箱：landy@jd.com 
