* 今日头条笔试题目：
* 找错：
** 下列代码的功能是把"hello, toutiao!"反转并输入，找出错误（不止一处）
~#include "stdlib.h"
#include "stdio.h"
#include "string.h"

int main(int argc, char* argv[]){
    char* scr = "hello, toutiao!";
    unsigned int len = strlen(scr);
    char* dst = (char*)malloc(len);
    unsigned int cnt = len;

    char* src_st_p = src[len];
    char* dst_st_p = dst;
    while (--cnt != -1){
        dst_st_p++ = src_st_p--;
    }

    printf("%s\n", dst);
    
    return 0;
}
~
* 编程题：
** 要求编写实现一个函数：给出一个二叉树的根结点，输出左右镜像变换后的二叉树的中序遍历
说明：
1. 数据结构可以自定义
2. 输入：已知a的根结点，a如下：
   1
  / \
  4  3
 /\
7 0 
   左右镜像变换后为b，b如下：
       1
      / \
      3 4
        /\
        0 7
   应输出b的中序遍历
** 编写一个函数
从一些概率不同的元素中，随机按概率选择并且返回。设第i个元素的概率是Pi。可以用浮点随机函数rand()
说明：
1. 函数输入：正整数数组。Pi代表每个元素可能被选择的权重.
   函数输出：选择的元素的下标
2. 例子：
   输入：{10，15，25}
   函数：保证3个元素的输出概率为 20%，30%，50%
   （第一个元素的概率： 10/(10+15+25) = 20%）
3. 在函数功能正确的前提下，使空间、时间复杂度尽可能低，函数会被调用多次
* 系统设计题：
对于每条要闻，用户可以对其进行评论，需求如下：
1. 用户可以对喜欢的评论点赞，评论的热度由点赞的数量决定，
2. 用户在浏览评论时，发现自己好友的评论是件很有意思的事，希望看到自己好友的评论，
3. 新评论比旧评论要优先显示
综合考虑1、2、3,设计一套算法，使得
1. 好友的评论优先显示
2. 然后显示热度最高的20条评论
3. 最后评论按时间倒序排列
要求:数据结构和算法自已设计,说明这样设计的原因(综合考虑时间、空间)
说明：
1. 拿阅兵新闻举例，这条新闻会被阅读3000万次，每次阅读都会显示评论，总评论数大于10万，
   最热的评论大于3万人点赞
2. 每个人的好友数控制在2000以内
3. 评论总是变化的，增加或者删除

* 推荐算法方向附加题：
有一堆带有标签{1，0}的数据集，每条带有标签的数据称作一个实例。
这堆数据有N个实例，每个实例有M个特征。
第i个实例的第j个特征，第i个实例的标签，即(i in [1,N],  j in [i, M])。
采用Logistic Regression对其建立模型，为了对未来没有标签的数据分类。
Logistic Regression的公式为：损失函数公式为:（具体公式见给出的照片）

要求：见给出的照片
